version: "3.9"
services:
#  web:
#   depends_on:
#     - postgres_db
#   build:
#     context: .
#     dockerfile: Dockerfile
#   image: yourstudypath-slim-burster:v1.0.0
#   environment:
#     - PORT=8020
#   env_file:
#     - .env
#   ports:
#     - "8001:8020"
#   command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
#   volumes:
#      - staticfiles:/app/staticfiles/

  postgres_db:
    image: postgres
    restart: always
    command: -p 5436
    env_file:
      - .env
    expose:
      - 5436
    ports:
      - "5436:5436"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis_db:
    image: redis
    restart: always
    expose:
      - 6389
    ports:
      - "6389:6389"
    volumes:
        - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6389


volumes:
  staticfiles:
    external: true
  postgres_data:
  redis_data: